import React from "react";

export default function TermsConditionsPage() {
  return (
    <div className="flex flex-col mt-4 pb-5 px-4 sm:px-8 md:px-16 lg:px-20">
      <h1 className="text-xl sm:text-4xl font-bold text-center">
        Terms of Use for ClickedArt.com
      </h1>
      <p className="text-base sm:text-paragraph font-semibold mt-2">Last Updated: 26 January 2025</p>
      <p className="mt-4 text-justify text-base sm:text-paragraph font-medium">
        Welcome to ClickedArt.com! These Terms of Use ("Terms") govern your
        access to and use of the website and services provided by ClickedArt.com
        ("Platform"). By accessing or using the Platform, you agree to be bound
        by these Terms. If you do not agree, please refrain from using the
        Platform.
      </p>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-paragraph font-bold">1. Definitions</h6>
      <div className="mt-2 space-y-2">
        <p className="text-justify">
          1.1. <strong>"Platform"</strong> refers to ClickedArt.com, including
          all associated websites, services, and tools.
        </p>
        <p className="text-justify">
          1.2. <strong>"User"</strong> refers to any individual or entity
          accessing the Platform, including photographers and buyers.
        </p>
        <p className="text-justify">
          1.3. <strong>"Photographer"</strong> refers to users who register to
          upload, share, and sell their photographs on the Platform.
        </p>
        <p className="text-justify">
          1.4. <strong>"Buyer"</strong> refers to users who purchase digital
          downloads or prints of photographs on the Platform.
        </p>
        <p className="text-justify">
          1.5. <strong>"Content"</strong> refers to images, text, metadata, and
          other materials uploaded by photographers or generated by the
          Platform.
        </p>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        2. Acceptance of Terms
      </h6>
      <div className="mt-2 space-y-2">
        <p>
          2.1. By registering, uploading content, purchasing, or otherwise
          interacting with the Platform, you acknowledge that you have read,
          understood, and agree to these Terms.
        </p>
        <p>
          2.2. These Terms may be updated from time to time. Continued use of
          the Platform after updates signifies acceptance of the revised Terms.
        </p>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        3. Account Registration and Management
      </h6>
      <div className="mt-2 space-y-2">
        <p className="text-justify">
          3.1. <strong>Eligibility:</strong> You must be at least 18 years old
          to register. For minors, a parent or legal guardian must supervise and
          consent.
        </p>
        <p className="text-justify">
          3.2. <strong>Account Security:</strong> Users are responsible for
          maintaining the confidentiality of their login credentials.
        </p>
        <p className="text-justify">
          3.3. <strong>Accurate Information:</strong> Users must provide
          accurate and up-to-date information during registration.
        </p>
        <p className="text-justify">
          3.4. <strong>Account Termination:</strong> ClickedArt reserves the
          right to suspend or terminate accounts for violation of these Terms or
          applicable laws.
        </p>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        4. Photographer Guidelines
      </h6>
      <div className="mt-2 space-y-2">
        <div>
          <p className="font-bold">4.1 Content Upload</p>
          <ul className="ml-6 list-disc list-inside">
            <li>
              Photographers are responsible for ensuring that their uploaded
              content complies with copyright laws and does not infringe on the
              rights of others.
            </li>
            <li>
              Content must meet the quality standards outlined in our Upload
              Guidelines.
            </li>
          </ul>
        </div>
        <div>
          <p className="font-bold">4.2 Monetization</p>
          <ul className="ml-6 list-disc list-inside">
            <li>
              Photographers can apply for monetization after registration
              approval.
            </li>
            <li>
              Royalty models:
              <ul className="list-disc list-inside ml-5">
                <li>Standard: 70% of net sales</li>
                <li>Exclusive: 80% of net sales</li>
              </ul>
            </li>
            <li>
              Taxes, including TDS, will be deducted as per government norms.
            </li>
          </ul>
        </div>
        <div>
          <p className="font-bold">4.3 Licensing and Usage</p>
          <ul className="ml-6 list-disc list-inside">
            <li>
              By uploading content, photographers grant ClickedArt a
              non-exclusive license to display, market, and sell their content.
            </li>
            <li>
              Photographers retain ownership of their content but must ensure it
              is not simultaneously sold with conflicting licenses elsewhere.
            </li>
          </ul>
        </div>
        <div>
          <p className="font-bold">4.4 Prohibited Content</p>
          <ul className="ml-6 list-disc list-inside">
            <li>
              Content must not include:
              <ul className="list-disc list-inside ml-5">
                <li>Nudity, hate speech, or violent imagery.</li>
                <li>Misleading or inaccurate metadata.</li>
                <li>Plagiarized or unlicensed images.</li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        5. Buyer Guidelines
      </h6>
      <div className="mt-2 space-y-2">
        <p className="font-bold">5.1. Purchasing Content</p>
        <ul className="ml-6 list-disc list-inside">
          <li>
            Buyers can purchase digital downloads or printed photographs based
            on the licensing options provided.
          </li>
          <li>
            All purchases are final, except in cases of damaged print orders.
          </li>
        </ul>
        <p className="font-bold">5.2. Licensing Terms</p>
        <ul className="ml-6 list-disc list-inside">
          <li>
            Buyers must adhere to the license terms specified at the time of
            purchase:
            <ul className="list-disc list-inside ml-5">
              <li>
                <strong>Standard License:</strong> Personal use only.
              </li>
              <li>
                <strong>Extended License:</strong> Commercial use permitted.
              </li>
            </ul>
          </li>
          <li>Exclusive licenses may be arranged by contacting support.</li>
        </ul>
        <p className="font-bold">5.3. Prohibited Use</p>
        <ul className="ml-6 list-disc list-inside">
          <li>
            Buyers must not:
            <ul className="list-disc list-inside ml-5">
              <li>Resell purchased content without explicit permission.</li>
              <li>Remove watermarks from preview images.</li>
              <li>Use content in illegal or unethical activities.</li>
            </ul>
          </li>
        </ul>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        6. Fees and Payments
      </h6>
      <div className="mt-2 space-y-2">
        <p>
          6.1. Prices displayed on the Platform are inclusive of applicable
          taxes unless stated otherwise.{" "}
        </p>
        <p>
          6.2. Payment gateways ensure secure transactions. ClickedArt is not
          liable for third-party payment gateway issues.{" "}
        </p>
        <p>
          6.3. Photographers and buyers are responsible for any transaction fees
          imposed by financial institutions.
        </p>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        7. Intellectual Property Rights
      </h6>
      <div className="mt-2 space-y-2">
        <p>7.1. Photographers retain ownership of their content.</p>
        <p>
          7.2. ClickedArt&apos;s logo, design, and functionality are protected
          by intellectual property laws.{" "}
        </p>
        <p>
          7.3. Users must not copy, reverse-engineer, or modify any part of the
          Platform.
        </p>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        8. Privacy and Data Protection
      </h6>
      <div className="mt-2 space-y-2">
        <p>
          8.1. Users’ data is collected and processed in accordance with our
          Privacy Policy.
        </p>
        <p>
          8.2. Sensitive data, such as payment details, is encrypted for
          security purposes.
        </p>
        <p>
          8.3. Photographers consent to display their profile and portfolio
          publicly on the Platform.
        </p>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        9. Dispute Resolution
      </h6>
      <div className="mt-2 space-y-2">
        <p>
          9.1. Buyers and photographers are encouraged to resolve disputes
          amicably.
        </p>
        <p>
          9.2. In unresolved cases, ClickedArt may mediate but is not obligated
          to arbitrate disputes.
        </p>
        <p>
          9.3. Legal disputes will be subject to the jurisdiction of courts in
          [Lucknow/Uttar Pradesh].
        </p>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        10. Prohibited Activities
      </h6>
      <div className="mt-2 space-y-2">
        <p>10.1. Users must not:</p>
        <ul className="list-disc list-inside ml-5">
          <li>Post false or misleading content.</li>
          <li>Attempt to hack or disrupt the Platform.</li>
          <li>Use the Platform for illegal activities.</li>
        </ul>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        11. Indemnification
      </h6>
      <div className="mt-2 space-y-2">
        <p>
          Users agree to indemnify ClickedArt, its affiliates, and employees
          against any claims, damages, or liabilities arising from their use of
          the Platform or breach of these Terms.
        </p>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        12. Limitation of Liability
      </h6>
      <div className="mt-2 space-y-2">
        <p>ClickedArt is not liable for:</p>
        <ul className="list-disc list-inside ml-5">
          <li>Loss of earnings for photographers.</li>
          <li>Errors in metadata provided by photographers.</li>
          <li>Issues arising from misuse of purchased content by buyers.</li>
        </ul>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">13. Termination</h6>
      <div className="mt-2 space-y-2">
        <p>
          13.1. ClickedArt reserves the right to suspend or terminate user
          accounts for violations of these Terms.
        </p>
        <p>
          13.2. Users may terminate their accounts voluntarily by contacting
          support.
        </p>
      </div>
      <hr className="border-2 my-5 border-surface-300" />
      <h6 className="text-base sm:text-paragraph font-bold">
        14. Contact Information
      </h6>
      <div className="mt-2 space-y-2">
        <p>
          For queries, feedback, or complaints, please contact ClickedArt at:
        </p>
        <ul className="list-disc list-inside ml-5">
          <li>Email: support@clickedart.com</li>
          <li>Phone: +91 7054001056</li>
        </ul>
      </div>
    </div>
  );
}
